server:
  port: 8086
  servlet:
    context-path: /api/config/v1

# Logging Configuration
logging:
  level:
    com.xyz.tms: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: tms-config-service
  # H2-Config
  datasource:
    url: jdbc:h2:mem:partnerconfig
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

